"""Best-effort generation of a ready-to-paste Lovelace dashboard card.

Deliberately does NOT write directly into Home Assistant's Lovelace
storage: there is no supported public API for a custom integration to
do that, and the closest internal one (`homeassistant.components.
lovelace.dashboard.LovelaceStorage`) risks corrupting or silently
clobbering a user's existing dashboard if HA's frontend has a
conflicting in-memory copy at the time of writing, and isn't stable
across HA versions. Instead this writes a plain YAML file into the
config directory, with this account's real entity IDs already filled
in, and raises a one-time persistent notification pointing at it --
the user still does the final "Add Card -> Manual -> paste" step
themselves, but never has to hunt down entity IDs by hand.

See docs/examples/wallbox-dashboard-card.yaml for the same card with
sanitized placeholder entity IDs, kept in the repo for reference.
"""
from __future__ import annotations

import logging
import os

import yaml
from homeassistant.components import persistent_notification
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er

from .const import CONF_STATION_NAME, DOMAIN

_LOGGER = logging.getLogger(__name__)

# (domain, unique_id suffix appended to f"{inv_sn}_", display name or
# None to use the entity's own name). Order here is the order tiles
# appear in the generated card.
_CARD_ROWS: list[tuple[str, str, str | None]] = [
    ("switch", "charging_switch", "Charging"),
    ("number", "max_current_setting", "Max current limit"),
    ("select", "charger_mode_select", "Charge mode"),
    ("sensor", "state", "State"),
    ("sensor", "charger_power", None),
    ("sensor", "charger_vol", None),
    ("sensor", "charger_cur", None),
    ("sensor", "charger_total_energy", None),
    ("sensor", "charger_per_energy", None),
    ("sensor", "charger_total_cost", None),
    ("sensor", "charger_per_cost", None),
    ("sensor", "charger_per_time", None),
    ("sensor", "phase", None),
    ("binary_sensor", "fault", None),
]


async def async_generate_dashboard_card(
    hass: HomeAssistant, entry: ConfigEntry, inv_sn: str
) -> None:
    """Write a ready-to-paste dashboard card YAML for this wallbox.

    Safe to call on every integration setup/reload: it just regenerates
    the file (picking up any entity_id renames), and only raises the
    one-time notification the first time the file is created.
    """
    ent_reg = er.async_get(hass)
    cards: list[dict] = []
    for domain, suffix, name in _CARD_ROWS:
        entity_id = ent_reg.async_get_entity_id(domain, DOMAIN, f"{inv_sn}_{suffix}")
        if entity_id is None:
            continue
        tile: dict = {"type": "tile", "entity": entity_id}
        if name:
            tile["name"] = name
        cards.append(tile)

    if not cards:
        _LOGGER.debug("No known entities registered yet, skipping dashboard card generation")
        return

    station_name = entry.data.get(CONF_STATION_NAME, inv_sn)
    card_config = {
        "type": "grid",
        "title": station_name,
        "columns": 2,
        "square": False,
        "cards": cards,
    }

    path = hass.config.path(f"renac_wallbox_dashboard_{inv_sn}.yaml")

    def _write_file() -> bool:
        is_new = not os.path.exists(path)
        with open(path, "w", encoding="utf-8") as f:
            f.write(
                "# Auto-generated by the RENAC Wallbox integration -- safe to delete,\n"
                "# it's regenerated (not required for the integration to work) on every\n"
                "# setup/reload. To use it: open a dashboard -> Edit Dashboard -> Add\n"
                "# Card -> scroll to \"Manual\" -> paste everything below this line.\n\n"
            )
            yaml.dump(card_config, f, allow_unicode=True, sort_keys=False)
        return is_new

    try:
        is_new = await hass.async_add_executor_job(_write_file)
    except OSError:
        _LOGGER.warning("Could not write dashboard card file to %s", path, exc_info=True)
        return

    if is_new:
        persistent_notification.async_create(
            hass,
            (
                f"A ready-to-paste dashboard card for **{station_name}** was generated "
                f"with your real entity IDs already filled in, at:\n\n`{path}`\n\n"
                "To use it: open any dashboard → **Edit Dashboard** → **Add Card** → "
                "scroll down to **Manual** → paste the file's contents. It groups the "
                "charging switch, mode, and current limit next to the key sensors, "
                "since Home Assistant's default device view can't put a switch next "
                "to a number entity."
            ),
            title="RENAC Wallbox dashboard card ready",
            notification_id=f"renac_wallbox_dashboard_{inv_sn}",
        )
